version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"  # HTTP and WebSocket on same port
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspaces:/app/workspaces
    restart: unless-stopped