version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "8080:80"      # Alternative HTTP port
      - "8443:443"     # Alternative HTTPS port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - node
    restart: unless-stopped
    networks:
      - openode-network

  node:
    build: .
    container_name: openode-node
    expose:
      - "3000"  # Only exposed internally to Caddy
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspaces:/app/workspaces
    restart: unless-stopped
    networks:
      - openode-network

volumes:
  caddy_data:
  caddy_config:

networks:
  openode-network:
    driver: bridge