version: '3.8'

services:
  app:
    build: .
    container_name: claude-web-terminal
    ports:
      - "3000:3000"
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WS_PORT=8081
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspaces:/app/workspaces
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx as reverse proxy (simpler than Caddy for debugging)
  nginx:
    image: nginx:alpine
    container_name: claude-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: always